//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeSql.ApplicationServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysjobstep
    {
        public System.Guid job_id { get; set; }
        public int step_id { get; set; }
        public string step_name { get; set; }
        public string subsystem { get; set; }
        public string command { get; set; }
        public int flags { get; set; }
        public string additional_parameters { get; set; }
        public int cmdexec_success_code { get; set; }
        public byte on_success_action { get; set; }
        public int on_success_step_id { get; set; }
        public byte on_fail_action { get; set; }
        public int on_fail_step_id { get; set; }
        public string server { get; set; }
        public string database_name { get; set; }
        public string database_user_name { get; set; }
        public int retry_attempts { get; set; }
        public int retry_interval { get; set; }
        public int os_run_priority { get; set; }
        public string output_file_name { get; set; }
        public int last_run_outcome { get; set; }
        public int last_run_duration { get; set; }
        public int last_run_retries { get; set; }
        public int last_run_date { get; set; }
        public int last_run_time { get; set; }
        public Nullable<int> proxy_id { get; set; }
        public Nullable<System.Guid> step_uid { get; set; }
    }
}
