//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeSql.ApplicationServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysjobserver
    {
        public System.Guid job_id { get; set; }
        public int server_id { get; set; }
        public byte last_run_outcome { get; set; }
        public string last_outcome_message { get; set; }
        public int last_run_date { get; set; }
        public int last_run_time { get; set; }
        public int last_run_duration { get; set; }
    }
}
