//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeSql.ApplicationServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysjobschedule
    {
        public Nullable<int> schedule_id { get; set; }
        public Nullable<System.Guid> job_id { get; set; }
        public int next_run_date { get; set; }
        public int next_run_time { get; set; }
    
        public virtual sysschedule sysschedule { get; set; }
    }
}
