//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeSql.ApplicationServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysjob
    {
        public System.Guid job_id { get; set; }
        public int originating_server_id { get; set; }
        public string name { get; set; }
        public byte enabled { get; set; }
        public string description { get; set; }
        public int start_step_id { get; set; }
        public int category_id { get; set; }
        public byte[] owner_sid { get; set; }
        public int notify_level_eventlog { get; set; }
        public int notify_level_email { get; set; }
        public int notify_level_netsend { get; set; }
        public int notify_level_page { get; set; }
        public int notify_email_operator_id { get; set; }
        public int notify_netsend_operator_id { get; set; }
        public int notify_page_operator_id { get; set; }
        public int delete_level { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_modified { get; set; }
        public int version_number { get; set; }
    }
}
